### ISSUE TITLE
is this broken now?

### ISSUE THREAD

**Issue by jbaylies** [maltfield/rtd-github-pages#6]
Just looking for a sanity check..

I'm getting a 404 page for my docs after pushing a change, then reverting the commit. https://jbaylies.github.io/Electrobrass_Encyclopedia/en/master/index.html https://github.com/jbaylies/Electrobrass_Encyclopedia

I also tried to set up a new repo and that 404'd as well. This was working before, so I'm not sure what changed.

**Comment by maltfield** [comment]
@jbaylies thanks for the bug report.

Yes it does appear that this was broken by a change made to git last year

 * https://github.com/git/git/commit/8959555cee7ec045958f9b6dd62e541affb7e7d9
 * https://github.com/BusKill/buskill-app/issues/65

```
fatal: detected dubious ownership in repository
```

**Comment by maltfield** [comment]
@jbaylies the latest commit should have fixed this issue. Please try to update your existing repo from upstream or create a new fork again.

If you're still having issues, then please let me know and I'll re-open and continue to investigate.
